#!/usr/bin/env python3
"""Conservative Jazz completion audit; creates JAZZ_DONE only if every gate passes."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs/jazz"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--create-done", action="store_true")
    args = parser.parse_args()
    subprocess.run([sys.executable, "scripts/generate_e2_e3_sections.py"], cwd=ROOT, check=True)
    status = json.loads((OUT / "overnight_status.json").read_text())
    audit = json.loads((OUT / "consistency_audit.json").read_text())
    e1 = json.loads((ROOT / "paper_sections/generated/jazz_12/summary.json").read_text())
    f2 = json.loads((OUT / "f2_generation_status.json").read_text())
    e3 = json.loads((OUT / "candidacy_final.json").read_text())
    e4 = json.loads((OUT / "personalwab_contradictions.json").read_text())
    reserved = {"HEADLINE_SCOPE", "HEADLINE_CELL_RECORD"}
    unresolved = {finding["code"] for finding in audit["findings"]}
    build = OUT / "build/paper_final.pdf"
    paper = ROOT / "paper_final.tex"
    gates = {
        "E1_pure_SPR_artifact": e1["scope"] == 12 and e1["n"] == 648,
        "F1_both_reserved_scope_packages": all((OUT / f"build/jazz_{scope}/review.pdf").exists() for scope in (12, 16)),
        "E2_complete_grid": bool(status["progress"]["e2_complete"]),
        "E2_paraphrase_trust": f2["trust_gate"] == "PASSED" and f2["human_signoff"],
        "F2_generated": bool(f2["generated"]),
        "E3_complete_pairs": bool(e3["complete"]),
        "F3_generated": (ROOT / "paper_sections/generated/jazz_f3.tex").exists(),
        "E4_exploratory_proxy": e4.get("analysis", "").startswith("EXPLORATORY") and e4.get("n_users") == 1000,
        "F4_only_reserved_findings": unresolved <= reserved and not audit["undefined_citations"]
                                     and all(not value["stale_sources"] for value in audit["generated_packages"].values()),
        "manuscript_build_current": build.exists() and build.stat().st_mtime >= paper.stat().st_mtime,
        "jazz_regression_tests": (OUT / "validation/jazz_tests_passed").exists(),
        "full_test_suite": (OUT / "validation/full_tests_passed").exists(),
        "sleep_assertion": bool(status["sleep_prevention"]["asserted"]),
    }
    complete = all(gates.values())
    lines = ["# Jazz final completion report", "",
             "Generated by `.venv/bin/python scripts/jazz_final_gate.py --create-done`.", "",
             "The two headline-scope findings are reserved for Jihan and are not silently resolved.", "",
             "| Requirement | Status | Evidence / generating command |", "|---|---|---|"]
    evidence = {
        "E1_pure_SPR_artifact": "`paper_sections/generated/jazz_12/summary.json`; `scripts/generate_jazz_results.py`",
        "F1_both_reserved_scope_packages": "`paper_sections/generated/jazz_{12,16}` and standalone review PDFs",
        "E2_complete_grid": "`outputs/jazz/overnight_status.json`; frozen prereg aggregator",
        "E2_paraphrase_trust": "`outputs/jazz/paraphrase_review.json`",
        "F2_generated": "`paper_sections/generated/jazz_f2.tex`",
        "E3_complete_pairs": "`outputs/jazz/candidacy_final.json`; `scripts/aggregate_profile_candidacy.py`",
        "F3_generated": "`paper_sections/generated/jazz_f3.tex`",
        "E4_exploratory_proxy": "`outputs/jazz/personalwab_contradictions.json`; `scripts/aggregate_personalwab_contradictions.py`",
        "F4_only_reserved_findings": "`outputs/jazz/consistency_audit.json`; `scripts/audit_jazz_consistency.py`",
        "manuscript_build_current": "`tectonic paper_final.tex --outdir outputs/jazz/build`",
        "jazz_regression_tests": "`.venv/bin/pytest -q tests/test_jazz_workflow.py`",
        "full_test_suite": "`.venv/bin/pytest -q`",
        "sleep_assertion": "`pmset -g assertions`; `outputs/jazz/overnight_status.json`",
    }
    for name, passed in gates.items():
        lines.append(f"| {name} | {'PASS' if passed else 'PENDING/BLOCKED'} | {evidence[name]} |")
    lines += ["", "## Remaining human-only decisions", "",
              "- Jihan must choose the 12-cell pure-SPR or separately labeled 16-cell mixed/archival headline scope.",
              "", "## Genuine blockers", ""]
    blockers = status["blockers"] or [{"scope": "none", "blocker": "none"}]
    lines += [f"- {item['scope']}: {item['blocker']}" for item in blockers]
    lines += ["", f"Overall non-reserved completion: **{'PASS' if complete else 'NOT YET COMPLETE'}**.", ""]
    (ROOT / "orchestration/jazz_final_completion_report.md").write_text("\n".join(lines))
    (OUT / "final_gate.json").write_text(json.dumps({"complete": complete, "gates": gates,
                                                       "reserved_findings": sorted(unresolved & reserved)}, indent=2) + "\n")
    if args.create_done and complete:
        (OUT / "JAZZ_DONE").write_text("Jazz non-reserved completion gates passed. See orchestration/jazz_final_completion_report.md\n")
    if not complete:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
